/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace Thrift.Service.Models.Enums
{
  public enum MessageType
  {
    Information = 0,
    Warning = 1,
  }
}
